WindowManager:   
    FirstWindow:
    SecondWindow:

<FirstWindow>:
    name:"first"
    
    NavigationLayout:
    
        ScreenManager:
    
            Screen:
                BoxLayout:
                    orientation: 'vertical'
                    spacing: dp(6)
                    MDToolbar:
                        title: "CovidApp"
                        elevation: 5
                        left_action_items: [['menu', lambda x: nav_drawer.set_state("open")]]
                    BoxLayout:
                        height: mdlab.texture_size[1]
                        MDLabel:
                            halign:"center"
                            valign:"top"
                            id: mdlab
                            text:"Welcome to Covid Application"
                            font_style: "H3"
                            color: "white"
                            padding_y: 30
                    
                    BoxLayout:
                        orientation: 'horizontal'
                        halign: 'center'
                        BoxLayout:
                            padding: dp(150), dp(0), dp(50), dp(0)

                            MDTextFieldRound:
                                id: mdtext
                                halign: "left"
                                font_size: 32
                                icon_left:"search-web"
                                hint_text:"Search a state"
                                normal_color: app.theme_cls.primary_color
                                color_active: 0, 1, 0, 1

                        BoxLayout:   
                            size_hint_x: .2
                            MDRoundFlatButton:
                                id: mdbu
                                text:"Search"
                                on_press: app.search_press()
                                
                    FloatLayout:
                        id: icon 
                    
                    MDBoxLayout:
                        padding: dp(0), dp(20), dp(0), dp(20)
                        Label:
                            id: prefer
                            halign: 'center'
                            color:"white"
                            font_style: "H4"
                            text:""
    
                    MDBoxLayout:
                        size_hint_y:None
                        halign: "center"
                        MDLabel:
                            id: info
                            font_style:"H4"
                            padding_x:250
                            color: "white"
                            height: 8 * dp(85)

                    Button:
                        size_hint_y:0.7
                        text:"All Preferites"
                        font_size: 22
                        on_release:
                            app.root.current = "second"
                            root.manager.transition.direction = "left"


        MDNavigationDrawer:
            id: nav_drawer
    
            BoxLayout:
                orientation: "vertical"
                padding: "8dp"
                spacing: "8dp"
                color:"white"
    
                AnchorLayout:
                    anchor_x: "left"
                    size_hint_y: None
                    height: avatar.height
    
                    Image:
                        id: avatar
                        size_hint: None, None
                        size: "56dp", "56dp"
                        source: "data/logo/kivy-icon-256.png"

                MDBoxLayout:
                    size_hint_y: None
                    height: title.texture_size[1]
                    MDLabel:
                        id: title
                        text: "CovidApp App 0.1"
                        color: "white"
                        font_style: "Button"
    
                MDBoxLayout:
                    size_hint_y: None
                    height: email_label.texture_size[1]
                    MDLabel:
                        id: email_label
                        text: "gabriele.sarti1@studenti.unimi.it"
                        color: "white"
                        font_style: "Caption"
    

                ScrollView:
    
                    MDList:
                        OneLineAvatarListItem:
                            text: "Favorites List"
                            on_press:app.show_favorites_dialog()
    
                            IconLeftWidget:
                                icon: "star-outline"
                                    
                        OneLineAvatarListItem:
                            text: "Info App"
                            on_press: app.show_app_info_dialog()
    
                            IconLeftWidget:
                                icon: "information-outline"

                        OneLineAvatarListItem:
                            text: "Contact"
                            on_press: app.show_contact_dialog()
                    
                            IconLeftWidget:
                                icon: "contact-mail-outline"    

<SecondWindow>:
    name: "second"
    MDBoxLayout
        MDLabel:
            size_hint_y:1.8
            halign: "center"
            id: prefer_title
            text:"Data for prefer"
            font_size:32
            color: "white"

    MDBoxLayout:
        size_hint_y: None       
        adaptive_height: True  
        Button:
            size_hint_y: 0.8
            text:"Go back"
            font_size: 22
            on_release:
                app.root.current = "first"
                root.manager.transition.direction = "right"
    

    MDBoxLayout:      
        padding: dp(20), dp(0), dp(20), dp(0)
        size_hint_x:0.3
        size_hint_y:0.1
        pos_hint:{"center_y":0.8,"center_x":0.5}
        Button:
            halign:"center"
            text: "Generate all the stats"
            on_press: app.prefer_text()

    MDBoxLayout:
        MDLabel:
            id: text_prefer
            font_style: "H6"
            color: "white"
            text:""